#print("Hello World")
#print("Hello Again")
#print("I like typing this. ")
#print("This is fun. ")
#print("Yay! Printing")
#print("I'd much ratger you 'not'.")
#print('I"said" do not touch this.')
#print("another line XD")
print("this line is the only one the computer will output because the hash makes the code be interpreted as a comment. ")